import React, {useEffect} from "react";
import Head from 'next/head'

import {allPostReq} from "../store/actions/allPostReq";
import {useAppDispatch} from "../hooks/useStore";
import PostList from "../components/PostList/PostList";
import styles from '../styles/Home.module.css'

const Home: React.FC = () => {
    const dispatch = useAppDispatch();
    useEffect(() => {
        dispatch(allPostReq())
    }, [dispatch])
    return (
        <div className={styles.container}>
            <Head>
                <title>Post and Comments app</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <PostList/>
            </main>
        </div>
    )
}
export default Home